= MicroProfile generated Application

With Jakarta MVC Demo Application as an example.

== Introduction

MicroProfile Starter has generated this MicroProfile application for you.

The generation of the executable jar file can be performed by issuing the
following command

    mvn clean package

This will create an executable jar file **mvc-demo-wildfly.jar** within
the _target_ maven folder. This can be started by executing the following
command

    java -jar target/mvc-demo-bootable.jar

To launch the test page, open your browser at the following URL

    http://localhost:8080/index.html


== Specification examples

By default, there is always the creation of a JAX-RS application class to define
the path on which the JAX-RS endpoints are available.

Also, a simple Hello world endpoint is created, have a look at the class
**HelloController**.

More information on MicroProfile can be found [here](https://microprofile.io/)

=== Config

Configuration of your application parameters. Specification
[here](https://microprofile.io/project/eclipse/microprofile-config)

The example class **ConfigTestController** shows you how to inject a
configuration parameter and how you can retrieve it programatically.

== Image Build

Commands to bu1ild the (single JAR) application:

  mvn clean package

Commands to build the Docker image:

  docker build -t mvc-app .
  docker run --rm -it mvc-app:latest

