title=About
date=2020-01-14
type=page
status=published
~~~~~~
== Me

My name is Gunther Rotsch. I am born in 1965 Germany and live now in
Mellingen, a small village close-by Zurich in Switzerland.

I studied Information Science at the University of Applied Science at
Mannheim in Germany. After finishing my study, I worked for a consulting
company for two years. After that I worked for 10 years as a freelancer
in software development projects. Then I was employed by consulting
companies and software application companies. Up until 2000 I mainly
developed with C ++ on Unix systems. After that my focus was on Java
Enterprise Systems.

== Skills and Interests

I have been developing business applications as a lead developer o
architect for 20+ years. Although my focus is on Java / Jarkata EE
(full stack), I am open to other technologies such as Web, JavaScript,
Python or Go.
In addition to architecture work and SOLID software design, I like to
work "hands-on" in programming. I am very familiar with modern approaches
such as clean coding, test-driven development and agile methods. The
quality of the developed products and application of modern development
processes are particularly close to my heart. This includes Static Code
analysis (SonarQube), test automation, continuous integration and
continuous deployment.
In the past four years, I have intensified with microservices /
self-contained services, cloud-native applications (Design for
Scalability, Resilience, Reliability, Monitoring), REST API Design
(Open API / Swagger).
I have practical experience in the deployment of containerized
applications with Docker, Kubernetes and OpenShift as well as in
setting up the necessary automated processes. Most recently, I also
have made experience with Ergon's Web Application Firewall and
roll-outs with Ansible, which complements my DevOps skills.
