title=JBake, Asciidoc and PlantUML
date=2020-02-01
type=post
tags=blog, asciidoc, jbake, plantuml
status=draft
~~~~~~
= JBake, Asciidoc and PlantUML
Gunther Rotsch
2020-02-01

Currently we found project PlantUML for writing UML diagrams-as-a-code. This is really hype to have everything in version control and it is always better to version text source that images or binary files. I was really happy that AsciiDoctor and JBake support this, but it was little bit tricky to get it work. And it is still not how it could be.

First problem was how to get it work. I’m using standalone JBake and all examples are pointing to Gradle builds. It was easier than I expect, just add following line to my jbake.properties:

```
asciidoctor.option.requires = asciidoctor-diagram
```

https://xpj.ninja/blog/2018/03/2018-03-21-why-jbake.html


Next step was to include generated diagrams into result pages. I was debuging JBake, looking into properties files, trying this and that, because generated images had wrong src attribute. Finally I figured, that it was as simple as adding ./ in front of the file name:


=== PlantUML

[plantuml, "./asciidoctor-sequence-diagram", "png"]
----
Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
----
